//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIApplication.Models
{
    using System;
    using System.Collections.Generic;

    public partial class films_vehicles
    {
        public int film_id { get; set; }
        public int vehicle_id { get; set; }
    }
}
